[tools]
    wally = "UpliftGames/wally@0.3.2"
    rojo = "rojo-rbx/rojo@7.4.1"
    selene = "Kampfkarren/selene@0.27.1"
    stylua = "johnnymorganz/stylua@0.20.0"
    rbxcloud = "Sleitnick/rbxcloud@0.14.0"
    remodel = "rojo-rbx/remodel@0.11.0"