[tools]
    wally = "UpliftGames/wally@0.3.1"
    rojo = "rojo-rbx/rojo@7.2.1"
    selene = "Kampfkarren/selene@0.22.0"
    stylua = "johnnymorganz/stylua@0.15.2"
    rbxcloud = "Sleitnick/rbxcloud@0.2.1"
    remodel = "rojo-rbx/remodel@0.11.0"