[tools]
    wally = "UpliftGames/wally@0.3.1"
    rojo = "rojo-rbx/rojo@7.2.1"
    selene = "Kampfkarren/selene@0.20.0"
    stylua = "johnnymorganz/stylua@0.14.2"
    rbxcloud = "Sleitnick/rbxcloud@0.2.1"