local Biarc = require(game.ReplicatedStorage.src.TrainSystem.Biarc)
local Math = require(game.ReplicatedStorage.src.TrainSystem.Math)
local P1 = Vector3.new(1,1,0)
local T1 = Vector3.new(0,0,-1)
local P2 = Vector3.new(0,0,-1)
local T2 = Vector3.new(1,0,0)

local Pm = Biarc:GetConnectionPoint(P1,T1,P2,T2)
local Tangent = Math:GetNextTangent(P1,Pm,T1)
print(Pm,Tangent)
