name: CI

on:
  push:
    branches:
    - main
    pull_request:
    - main

jobs:

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:


    - uses: LPGhatguy/aftman@v0.2.7
      name: Install Aftman
      with:
        version: "^0.2.7"
        token: ${{ SECRETS.GITHUB_TOKEN }}

    - name: Lint
      run: |
        selene ./src

  style: 
    name: Styling
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: JohnnyMorganz/stylua-action@v1
      with:
       token: ${{ secrets.GITHUB_TOKEN }}
       version: latest # NOTE: we recommend pinning to a specific version in case of formatting changes
        # CLI arguments
       args: --check .