name: Deploy


on:
  push:
    branches:
    - main
    pull_request:
    - main


jobs:

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - uses: ok-nick/setup-aftman@v0.1.0
      name: Install Aftman
      with:
        version: "v0.2.6"
        trust-check: false
        token: ${{ SECRETS.GITHUB_TOKEN }}

    - run: rojo --version

    - run: rojo build default.project.json -o Train-System.rbxl

    - run: rbxcloud experience publish --filename Train-System.rbxl  --place-id 11460400865 --universe-id 4074292350 --version-type published --api-key ${{ secrets.API_KEY }}
