name: Deploy

on:
  workflow_run:
    workflows: ["CI"]
    branches: [Staging]
    types: 
      - completed


jobs:

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - uses: Roblox/setup-foreman@v1
      name: Install Foreman
      with:
        version: "^1.0.0"
        token: ${{ SECRETS.GITHUB_TOKEN }}

    - run: rojo build -o Train-System.rbxl

    - run: rbxcloud experience publish --filename Train-System.rbxl  --place-id 11460457200 --universe-id 4074309530 --version-type published --api-key ${{ secrets.API_KEY }}
